name: lnm_backend

x-base-backend: &base-backend
  build:
    context: ../
    dockerfile: docker/images/dev.Dockerfile
  working_dir: /opt/api
  env_file:
    - ../.env
  volumes:
    - ../app:/opt/api/app
    - ../Makefile:/opt/api/Makefile
    - ../poetry.lock:/opt/api/poetry.lock
    - ../pyproject.toml:/opt/api/pyproject.toml
    - ../ecommerce.db:/opt/api/ecommerce.db

services:
  api:
    <<: *base-backend
    container_name: lnm-backend-api
    command: [ "make", "run-dev-server" ]
    ports:
      - "8010:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: sync
          path: ../app
          target: /opt/api/app
          ignore:
            - __pycache__/
            - "*.pyc"
            - "*.log"
        - action: rebuild
          path: ../poetry.lock
          
  # To view logs in real-time in UI
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
